/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Clock_1.h"
#include "PWM_RESET.h"
#include "PWM_R_CW_aliases.h"
#include "PWM_R_CW.h"
#include "PWM_L_CW_aliases.h"
#include "PWM_L_CW.h"
#include "PWM_R_CCW_aliases.h"
#include "PWM_R_CCW.h"
#include "PWM_L_CCW_aliases.h"
#include "PWM_L_CCW.h"
#include "PWM_L.h"
#include "PWM_R.h"
#include "Encoder_L_aliases.h"
#include "Encoder_L.h"
#include "Encoder_R_aliases.h"
#include "Encoder_R.h"
#include "Encoder_L_Timer.h"
#include "ENCODER_R_OVF_ISR.h"
#include "ENCODER_TMR_RESET.h"
#include "Encoder_R_Timer.h"
#include "ENCODER_L_OVF_ISR.h"
#include "UART.h"
#include "tx_isr.h"
#include "rx_isr.h"
#include "ENC_L_ISR.h"
#include "ENC_R_ISR.h"
#include "ROBOT_ID_REG.h"
#include "Clock_2.h"
#include "DIP_0_aliases.h"
#include "DIP_0.h"
#include "DIP_1_aliases.h"
#include "DIP_1.h"
#include "DIP_2_aliases.h"
#include "DIP_2.h"
#include "DIP_3_aliases.h"
#include "DIP_3.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

